### ISSUE TITLE
Outdated example in the personalized branch

### ISSUE THREAD

**Issue by markkuriekkinen** [apluslms/aplus-manual#4]
The personalized branch in this repository contains an outdated example of the personalized exercise functionality. It does not utilize the personalized instance files properly in the grader since it does not read them through the mounting point `/personalized_exercise/` (it did not exist in the early containers).

I have updated the `aplus-manual` repository with personalized exercise examples that work with Docker and use the special mounting point to read the instance files (in `run.sh`).

**Comment by raphendyr** [comment]
Removed old branch. Refer to `manual` for help with personalized exercises.
